name: Rerun Jira PR Checks
run-name: Rerunning Jira PR checks
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  rerun-pr-check:
    name: Rerun Jira PR Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Rerun Jira PR Checks
        run: .github/actions/rerun-jira-pr-checks
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_OWNER: $GITHUB_REPOSITORY_OWNER
          REPO: $GITHUB_REPOSITORY
